# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firmaListesiUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(449, 459)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 401, 341))
        self.listWidget.setObjectName("listWidget")
        self.pbFirmaDuzenle = QtWidgets.QPushButton(Form)
        self.pbFirmaDuzenle.setGeometry(QtCore.QRect(20, 370, 141, 36))
        self.pbFirmaDuzenle.setObjectName("pbFirmaDuzenle")
        self.pbFirmaSil = QtWidgets.QPushButton(Form)
        self.pbFirmaSil.setGeometry(QtCore.QRect(280, 370, 141, 36))
        self.pbFirmaSil.setObjectName("pbFirmaSil")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pbFirmaDuzenle.setText(_translate("Form", "Firma Düzenle"))
        self.pbFirmaSil.setText(_translate("Form", "Firma Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
