# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\kayitDuzenle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kayitDuzenle(object):
    def setupUi(self, kayitDuzenle):
        kayitDuzenle.setObjectName("kayitDuzenle")
        kayitDuzenle.resize(600, 700)
        self.cbFirmaAdi = QtWidgets.QComboBox(kayitDuzenle)
        self.cbFirmaAdi.setGeometry(QtCore.QRect(50, 30, 231, 30))
        self.cbFirmaAdi.setObjectName("cbFirmaAdi")
        self.pbKayitGoster = QtWidgets.QPushButton(kayitDuzenle)
        self.pbKayitGoster.setGeometry(QtCore.QRect(320, 30, 100, 30))
        self.pbKayitGoster.setObjectName("pbKayitGoster")
        self.twAyrintilar = QtWidgets.QTableWidget(kayitDuzenle)
        self.twAyrintilar.setGeometry(QtCore.QRect(50, 100, 531, 441))
        self.twAyrintilar.setObjectName("twAyrintilar")
        self.twAyrintilar.setColumnCount(5)
        self.twAyrintilar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twAyrintilar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAyrintilar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAyrintilar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAyrintilar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAyrintilar.setHorizontalHeaderItem(4, item)
        self.pbDuzenle = QtWidgets.QPushButton(kayitDuzenle)
        self.pbDuzenle.setGeometry(QtCore.QRect(50, 570, 180, 30))
        self.pbDuzenle.setObjectName("pbDuzenle")
        self.pbSil = QtWidgets.QPushButton(kayitDuzenle)
        self.pbSil.setGeometry(QtCore.QRect(300, 570, 180, 30))
        self.pbSil.setObjectName("pbSil")

        self.retranslateUi(kayitDuzenle)
        QtCore.QMetaObject.connectSlotsByName(kayitDuzenle)

    def retranslateUi(self, kayitDuzenle):
        _translate = QtCore.QCoreApplication.translate
        kayitDuzenle.setWindowTitle(_translate("kayitDuzenle", "Kayıt Düzenle"))
        self.pbKayitGoster.setText(_translate("kayitDuzenle", "Kayıtlar Göster"))
        item = self.twAyrintilar.horizontalHeaderItem(0)
        item.setText(_translate("kayitDuzenle", "#id"))
        item = self.twAyrintilar.horizontalHeaderItem(1)
        item.setText(_translate("kayitDuzenle", "İşlem Tipi"))
        item = self.twAyrintilar.horizontalHeaderItem(2)
        item.setText(_translate("kayitDuzenle", "Tarih"))
        item = self.twAyrintilar.horizontalHeaderItem(3)
        item.setText(_translate("kayitDuzenle", "Tutar"))
        item = self.twAyrintilar.horizontalHeaderItem(4)
        item.setText(_translate("kayitDuzenle", "Açıklama"))
        self.pbDuzenle.setText(_translate("kayitDuzenle", "Seçili Kaydı Düzenle"))
        self.pbSil.setText(_translate("kayitDuzenle", "Seçili Kaydı Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kayitDuzenle = QtWidgets.QWidget()
    ui = Ui_kayitDuzenle()
    ui.setupUi(kayitDuzenle)
    kayitDuzenle.show()
    sys.exit(app.exec_())
