# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("background-color: rgb(190, 248, 255);")
        self.lnKullanici = QtWidgets.QLabel(Form)
        self.lnKullanici.setGeometry(QtCore.QRect(10, 40, 81, 19))
        self.lnKullanici.setObjectName("lnKullanici")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(110, 30, 121, 36))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 184, 156);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 80, 121, 36))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 184, 156);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lnSifre = QtWidgets.QLabel(Form)
        self.lnSifre.setGeometry(QtCore.QRect(10, 90, 81, 19))
        self.lnSifre.setObjectName("lnSifre")
        self.pbGiris = QtWidgets.QPushButton(Form)
        self.pbGiris.setGeometry(QtCore.QRect(110, 150, 121, 36))
        self.pbGiris.setObjectName("pbGiris")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lnKullanici.setText(_translate("Form", "Kullanıcı Adı"))
        self.lnSifre.setText(_translate("Form", "Şifre"))
        self.pbGiris.setText(_translate("Form", "Giriş"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
