# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odemeGiris.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(700, 250)
        self.deOdemeTarihi = QtWidgets.QDateEdit(widget)
        self.deOdemeTarihi.setGeometry(QtCore.QRect(10, 60, 120, 30))
        self.deOdemeTarihi.setObjectName("deOdemeTarihi")
        self.cbFirmaAdi = QtWidgets.QComboBox(widget)
        self.cbFirmaAdi.setGeometry(QtCore.QRect(150, 60, 300, 30))
        self.cbFirmaAdi.setObjectName("cbFirmaAdi")
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(10, 20, 120, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 120, 30))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(widget)
        self.label_4.setGeometry(QtCore.QRect(540, 20, 120, 30))
        self.label_4.setObjectName("label_4")
        self.leOdemeTutar = QtWidgets.QLineEdit(widget)
        self.leOdemeTutar.setGeometry(QtCore.QRect(530, 60, 120, 30))
        self.leOdemeTutar.setObjectName("leOdemeTutar")
        self.pushButton = QtWidgets.QPushButton(widget)
        self.pushButton.setGeometry(QtCore.QRect(530, 140, 120, 30))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(widget)
        self.label_5.setGeometry(QtCore.QRect(160, 100, 120, 30))
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(widget)
        self.textEdit.setGeometry(QtCore.QRect(150, 140, 300, 60))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Gelen Ödeme Giriş Ekranı"))
        self.label.setText(_translate("widget", "Ödeme Tarihi"))
        self.label_2.setText(_translate("widget", "Firma İsmi"))
        self.label_4.setText(_translate("widget", "Ödeme Tutar"))
        self.pushButton.setText(_translate("widget", "Kaydet"))
        self.label_5.setText(_translate("widget", "Açıklama"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_widget()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
